// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjYqSI9jU7t3cShzTK6SfEQ6be3dTKtdQ',
    appId: '1:457043420157:web:613c9c7fb8cbc74e202f94',
    messagingSenderId: '457043420157',
    projectId: 'tilt-maze-3f4c2',
    authDomain: 'tilt-maze-3f4c2.firebaseapp.com',
    storageBucket: 'tilt-maze-3f4c2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxQET-0yyFAE6ORj5lnVcgPlhA5F1rabQ',
    appId: '1:457043420157:android:78d383d032494839202f94',
    messagingSenderId: '457043420157',
    projectId: 'tilt-maze-3f4c2',
    storageBucket: 'tilt-maze-3f4c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyKkbnYxejN4y35vzfAhGXuslR6fWjfzQ',
    appId: '1:457043420157:ios:511988bbc8ec778f202f94',
    messagingSenderId: '457043420157',
    projectId: 'tilt-maze-3f4c2',
    storageBucket: 'tilt-maze-3f4c2.firebasestorage.app',
    iosBundleId: 'com.example.ballGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyKkbnYxejN4y35vzfAhGXuslR6fWjfzQ',
    appId: '1:457043420157:ios:511988bbc8ec778f202f94',
    messagingSenderId: '457043420157',
    projectId: 'tilt-maze-3f4c2',
    storageBucket: 'tilt-maze-3f4c2.firebasestorage.app',
    iosBundleId: 'com.example.ballGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjYqSI9jU7t3cShzTK6SfEQ6be3dTKtdQ',
    appId: '1:457043420157:web:901e10ac7653875e202f94',
    messagingSenderId: '457043420157',
    projectId: 'tilt-maze-3f4c2',
    authDomain: 'tilt-maze-3f4c2.firebaseapp.com',
    storageBucket: 'tilt-maze-3f4c2.firebasestorage.app',
  );
}
